ElectricPower <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, as.is = TRUE)
ElectricPowerData <- subset(ElectricPower, Date == "1/2/2007" | Date == "2/2/2007")
DatesAndTimes <- paste(ElectricPowerData$Date, ElectricPowerData$Time)
Times <- strptime(DatesAndTimes, format="%d/%m/%Y %H:%M:%S")
png("plot3.png")
plot(Times, ElectricPowerData$Sub_metering_1, xlab="", ylab="Energy sub metering", type="n")
lines(Times, ElectricPowerData$Sub_metering_1, col="black")
lines(Times, ElectricPowerData$Sub_metering_2, col="red")
lines(Times, ElectricPowerData$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col=c("black", "red", "blue"))
dev.off()